"use strict";
exports.__esModule = true;
var artLeche = new Articulo(123, "Leche", 110, "litro");
var artQueso = new Articulo(234, "Queso", 260, "gramo");
var artPan = new Articulo(345, "Pan", 100, "gramo");
var artFideos = new Articulo(678, "Fideos", 95, "gramo");
var artCerveza = new Articulo(891, "Cerveza", 250, "litro");
var cliente01 = new Cliente("1234abc", 'Monotributista', 20123456788);
var factura01 = new Factura("A", 1, 100, TipoPago.E, new Date("01/12/2021 13:00"), cliente01);
var detArt01 = new DetalleFactura(2, factura01, artLeche);
var detArt02 = new DetalleFactura(4, factura01, artCerveza);
factura01.detalleFactura.push(detArt01);
factura01.detalleFactura.push(detArt02);
// factura01.calcularTotalItems();
// factura01.calcularTotalFinal();
var factura02 = new Factura("B", 2, 200, TipoPago.CC, new Date("01/24/2021 14:56"), cliente01);
var detArt03 = new DetalleFactura(4, factura02, artFideos);
var detArt04 = new DetalleFactura(1, factura02, artQueso);
factura02.detalleFactura.push(detArt03);
factura02.detalleFactura.push(detArt04);
// factura02.calcularTotalItems();
// factura02.calcularTotalFinal();
var factura03 = new Factura("B", 2, 200, TipoPago.CC, new Date("01/24/2021 14:56"), cliente01);
var detArt05 = new DetalleFactura(2, factura03, artPan);
var detArt06 = new DetalleFactura(6, factura03, artCerveza);
factura03.detalleFactura.push(detArt05);
factura03.detalleFactura.push(detArt06);
// factura03.calcularTotalItems();
// factura03.calcularTotalFinal();
cliente01.facturas.push(factura01);
cliente01.facturas.push(factura02);
cliente01.facturas.push(factura03);
var ulElement = document.getElementById("respB");
cliente01.facturas.forEach(function (factura) {
    factura.calcularTotalItems();
    factura.calcularTotalFinal();
    var liElement = document.createElement('li');
    ulElement.appendChild(liElement);
    liElement.innerHTML += "EL cliente n\u00B0" + cliente01.numero + ", factura n\u00B0" + factura.numero + ", total : " + factura.totalFinal;
});
